import airForce1 from "../../assets/images/MenImg/531-5319025_nike-af-1-07-lo-nike-air-force-jukebox-bg-removed.png";
import ultraboost23 from "../../assets/images/MenImg/Adidas Ultraboost-jukebox-bg-removed.png";
import adizero from "../../assets/images/MenImg/Adidasadizero-jukebox-bg-removed.png";
import runfalcon from "../../assets/images/MenImg/Adidasrunfalcon-jukebox-bg-removed.png"
import nb574 from "../../assets/images/MenImg/download (1)-jukebox-bg-removed.png";
import freshFoamX from "../../assets/images/MenImg/download (2)-jukebox-bg-removed.png";
import superstar from "../../assets/images/MenImg/download (3)-jukebox-bg-removed.png";
import suedeClassic from "../../assets/images/MenImg/download (4)-jukebox-bg-removed.png";
import reactInfinity from "../../assets/images/MenImg/download (5)-jukebox-bg-removed.png";
import nb550 from "../../assets/images/MenImg/download (6)-jukebox-bg-removed.png";
import nb990 from "../../assets/images/MenImg/new-balance-9060-jukebox-bg-removed.png";
import airMax270 from "../../assets/images/MenImg/Nike-air-max-jukebox-bg-removed.png";
import airZoomPegasus from "../../assets/images/MenImg/Nike-air-zoom-jukebox-bg-removed.png";
import revolution7 from "../../assets/images/MenImg/Nikerevolution-jukebox-bg-removed.png";
import pumaVelocityNitro from "../../assets/images/MenImg/Puma3-jukebox-bg-removed.png";
import pumaDeviateNitro from "../../assets/images/MenImg/PumaDevite-jukebox-bg-removed.png";
import pumaRSX from "../../assets/images/MenImg/PumaRsX-jukebox-bg-removed.png";
import reebokNano from "../../assets/images/MenImg/Reebok4-jukebox-bg-removed.png";
import reebokClassic from "../../assets/images/MenImg/download-jukebox-bg-removed.png";


export const products = [
  {
    id: 1,
    image: airZoomPegasus,
    brand: "Nike",
    name: "Air Zoom Pegasus 40",
    category: "Running",
    dark: true,
    rating: 4.8,
    reviews: 1248,
    price: 7999,
    originalPrice: 9999,
    badge: "Best Seller",
  },
  {
    id: 2,
    image: airMax270,
    brand: "Nike",
    name: "Air Max 270",
    category: "Lifestyle",
    dark: false,
    rating: 4.7,
    reviews: 982,
    price: 8999,
    originalPrice: 11999,
    badge: "Trending",
  },
  {
    id: 3,
    image: ultraboost23,
    brand: "Adidas",
    name: "Ultraboost 23",
    category: "Running",
    dark: true,
    rating: 4.9,
    reviews: 1450,
    price: 10999,
    originalPrice: 13999,
    badge: "Premium",
  },
  {
    id: 4,
    image: adizero,
    brand: "Adidas",
    name: "NMD R1 V2",
    category: "Lifestyle",
    dark: false,
    rating: 4.5,
    reviews: 670,
    price: 8999,
    originalPrice: 10999,
    badge: "Popular",
  },
  {
    id: 5,
    brand: "Puma",
    image: pumaRSX,
    name: "RS-X Bold",
    category: "Sneakers",
    dark: true,
    rating: 4.4,
    reviews: 456,
    price: 6499,
    originalPrice: 8499,
    badge: "20% Off",
  },
  {
    id: 6,
    brand: "Puma",
    image: pumaVelocityNitro,
    name: "Velocity Nitro",
    category: "Running",
    dark: true,
    rating: 4.5,
    reviews: 734,
    price: 7499,
    originalPrice: 9499,
    badge: "Sale",
  },
  {
    id: 7,
    image: reebokNano,
    brand: "Reebok",
    name: "Nano X3",
    category: "Training",
    dark: false,
    rating: 4.6,
    reviews: 432,
    price: 7499,
    originalPrice: 9499,
    badge: "Gym Pick",
  },
  {
    id: 8,
    brand: "Reebok",
    image: reebokClassic,
    name: "Classic Leather",
    category: "Lifestyle",
    dark: false,
    rating: 4.4,
    reviews: 889,
    price: 4999,
    originalPrice: 6499,
    badge: "Sale",
  },
  {
    id: 9,
    brand: "New Balance",
    image: nb574,
    name: "574 Core",
    category: "Casual",
    dark: false,
    rating: 4.5,
    reviews: 334,
    price: 5499,
    originalPrice: 6999,
    badge: "Popular",
  },
  {
    id: 10,
    image: nb990,
    brand: "New Balance",
    name: "990v5",
    category: "Lifestyle",
    dark: true,
    rating: 4.8,
    reviews: 234,
    price: 14999,
    originalPrice: 17999,
    badge: "Premium",
  },
  {
    id: 11,
    image: airForce1,
    brand: "Nike",
    name: "Air Force 1 '07",
    category: "Lifestyle",
    dark: true,
    rating: 4.9,
    reviews: 3421,
    price: 7999,
    originalPrice: 9999,
    badge: "Icon",
  },
  {
    id: 12,
    brand: "Nike",
    image: reactInfinity,
    name: "React Infinity Run",
    category: "Running",
    dark: true,
    rating: 4.6,
    reviews: 765,
    price: 9499,
    originalPrice: 11499,
    badge: "New",
  },
  {
    id: 13,
    brand: "Adidas",
    image: superstar,
    name: "Superstar Classic",
    category: "Casual",
    dark: false,
    rating: 4.6,
    reviews: 2200,
    price: 6999,
    originalPrice: 8499,
    badge: "Classic",
  },
  {
    id: 14,
    image: suedeClassic,
    brand: "Puma",
    name: "Suede Classic XXI",
    category: "Casual",
    dark: false,
    rating: 4.3,
    reviews: 520,
    price: 5499,
    originalPrice: 6999,
    badge: null,
  },
  {
    id: 15,
    image: freshFoamX,
    brand: "New Balance",
    name: "Fresh Foam X",
    category: "Running",
    dark: true,
    rating: 4.7,
    reviews: 610,
    price: 8999,
    originalPrice: 10999,
    badge: "New Arrival",
  },
];